<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\Quizr.App\Quizr.App.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="TUnit" />
        <PackageReference Include="AwesomeAssertions" />
        <PackageReference Include="NSubstitute" />
        <PackageReference Include="Testcontainers.PostgreSql" />
        <PackageReference Include="Microsoft.Extensions.TimeProvider.Testing" />
    </ItemGroup>

    <ItemGroup>
        <Using Include="TUnit.Core" />
    </ItemGroup>
</Project>
